### ISSUE TITLE
Implementación de permisos relacionados y autoselección, planificación y diseño 

### ISSUE THREAD

**Issue by FiorellaBonilla** [Solvosoft/django-gentelella-widgets#65]
- Se implementará una nueva funcionalidad para el sistema de permisos, el cual consiste en relacionar los permisos complementarios que posee cada usuario y a su vez sugerirle si desea agregar dichos permisos relacionados.

- Se definirá un modelo llamado "PermissionDependency", el cual en DJango se  utiliza para representar las relaciones de dependencia entre diferentes permisos. Se definirá la clase PermissionDependency como un modelo que va a heredar de models.Model. Cada instancia de este modelo, va almacenar dos permisos: el permiso de origen y el permiso dependiente.

- Dentro de la clase van haber dos campo definidos, los cuales utilizarán un modelo models.ForeignKey. Cada campo va a representar una relación con el modelo Permission, el cual en Django maneja los permisos de usuario. El campo source_permission, va a establecer una relación con el permiso de origen en la relacion de dependencia. Por otro lado, se utilizará el atributo related_name, el cual establece un nombre inverso para la relación, lo que va a permitir acceder a las dependencias desde un objeto Permission.

- Se definirá un campo dependent_permission, el cual va a establecer una relación con el permiso dependiente en la relación de dependencia. Al igual que este campo, se utilizará un on_delete=models.CASCADE, donde este nos va a indicar que si el permiso dependiente se elimina, también se va a eliminar todas las dependencias asociadas a él.

- Se establecerá una clase Meta, la cual va a establecer la opción de unique_together.Esta opción va a asegurar que no puedan haber múltiples instancias de PermissionDependency con la misma combinación de source_permission y dependent_permission.

- Se creará un nuevo archivo llamado PermissionDependency , dentro de la carpeta djgentelella, donde se definirá una función llamada create_permission_dependency que tomará dos argumentos: source_permission_codename y dependent_permission_codename. EL objetivo de esta función será obtener instancias de los permisos utilizando (codename). Luego se utilizará un método denominado get_or_create de PermissionDependency.objects para poder obtener una relación de dependencia ya existente o crear una nueva relación de dependencia entre los permisos source_permission y dependent_permission. Y el resultado de esta función se guardarán en las variables permission_dependency y created

- Además, vamos a tener un if, donde si created es true, va a significar que se creó una nueva relación y se va a imprimir un mensaje indicando que se creó una dependencia. Por otro lado, si created es false, nos va a indicar que ya había una relación y se imprime un mensaje indicando la dependencia existente.

- En caso de que alguna de las instancias de permiso no exista (es decir, Permission.DoesNotExist), se imprime un mensaje indicando que el permiso no se encontró.
Se crearán relaciones de dependencia llamando a la función create_permission_dependency.

- Se utilizará un script de handlePermissionClick, el cual se va a llamar cuando se haga click en un checkbox. Donde tomará el ID, el nombre y el estado del checkbox y realiza una solicitud AJAX al servidor, donde este va a guardar el estado del permiso. También se definirá un script con una función showSwal para mostrar una alerta visual, haciendo uso de la biblioteca de SweetAlert.

¿Dónde ?

 - Se trabajarán en dos diferentes archivos , tales como PermissionDependency.py: , dentro de este archivo, encontraremos la lógica relacionada a la implementación de los permisos relacionados y autoselección. Por otra parte, tenemos permissions_management.html, el cual contendrá la estructura de los checkbox a utilizar.
- Se creará el modelo PermissionDependency , estos se van a construir dentro del archivo models.py.

¿Por qué?
- Esta implementación es de suma importancia dentro del sistema de permisos, puesto que facilitará la interacción del usuario, en el momento de seleccionar los permisos que le corresponden. Por ejemplo, si el usuario desea poder realizar la acción de añadir, primeramente debe poseer el permiso de ver, por lo que en un caso de esta índole, la nueva funcionalidad que se le añadirá al sistema, facilitará la identificación de los permisos principales y sus relacionados.

**Comment by MichaelSuarez22** [comment]
Después de investigar más a profunidad acerca de cómo implementar la solución del código para el sistema de permisos, se dedujo que la mejor manera para mostrar los permisos relacionados de un permiso específico es creando una sección dentro del modal, el cual permite mostrar y ocultar los permisos relacionados.
